title: Rizqah Meniers # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from Explore DS Academy with a Data Science certificate(NQF5), including a BI consulting internship at Decision Inc.
  I am currently working personal projects and building on my data analytics skills.
  <br><br>
  <a href="https://www.linkedin.com/in/rizqahmeniers19/">View My LinkedIn Profile</a> 
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
