title: Rizqah Meniers # your name (or website title) here
logo: "/images/Rizqah.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have always been passionate about the concept of data. 
  After exploring my strengths, I had the opportunity to complete a data science program, learning data science fundamentals and machine learning techniques.
  This only enhanced my growing love for working with data. I aim to continue to learn more about the impact data has in our everyday lives.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/rizqahmeniers19/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
