title: Rizqah Meniers # your name (or website title) here
logo: <img src="/images/Rizqah.png" width="30"> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My portfolio
  <br><br>
  <a href="https://www.linkedin.com/in/rizqahmeniers19/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
